download_directory: C:\Users\Cindy\Downloads
urls: 
  - www.domain.com
  - mail.domain.com
  - domain.com
chromedriver_path: C:\Users\Cindy\Downloads\chromedriver.exe
cpanel:
  url: https://domain.com.au/cpanel
  username: Cindy
  password: CorrectHorseBatteryStaple
